<?php

declare(strict_types=1);

/**
 * Copyright 2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category  Horde
 * @copyright 2026 The Horde Project
 * @license   http://www.horde.org/licenses/lgpl21 LGPL 2.1
 * @package   Core
 */

namespace Horde\Core\Service;

use Horde\Core\Config\RegistryState;
use Horde\Core\Middleware\DefaultStack;
use Horde\Http\Uri;
use Horde\Routes\GroupMapper;
use RuntimeException;

/**
 * Compiles routes from all registered apps into an opcacheable PHP file.
 *
 * Encapsulates the full compilation pipeline: iterating apps from RegistryState,
 * building a GroupMapper with per-app groups, including route definition files,
 * and writing the compiled output.
 *
 * No CLI or HTTP assumptions — usable from bin scripts, web admin panels, or
 * installer plugins.
 */
class RoutesCompiler
{
    public function __construct(
        private readonly RegistryState $registryState,
        private readonly string $configBase,
        private readonly string $cacheDir,
    ) {}

    /**
     * Compile all application routes and write the cache file.
     *
     * @throws RuntimeException If cache directory cannot be created or file cannot be written
     */
    public function compile(): RoutesCompilerResult
    {
        $mapper = new GroupMapper();
        $mapper->setDefaultStack(DefaultStack::get());

        $appCount = 0;
        $routeCount = 0;

        foreach ($this->registryState->toArray() as $app => $config) {
            $status = $config['status'] ?? 'active';
            if (!in_array($status, ['active', 'notoolbar', 'hidden', 'admin'])) {
                continue;
            }

            $fileroot = $config['fileroot'] ?? null;
            $webroot = $config['webroot'] ?? null;
            if (!$fileroot || !$webroot) {
                continue;
            }

            $routeFile = $fileroot . '/config/routes.php';
            if (!file_exists($routeFile)) {
                continue;
            }

            $uri = new Uri($webroot);
            $beforeCount = count($mapper->getMatchList());

            $mapper->group([
                'prefix' => rtrim($uri->getPath(), '/'),
                'host' => $uri->getHost() !== '' ? $uri->getHost() : null,
                'scheme' => $uri->getScheme() !== '' ? $uri->getScheme() : null,
                'port' => $uri->getPort(),
                'defaults' => ['app' => $app],
            ], function (GroupMapper $m) use ($routeFile, $fileroot, $app) {
                $mapper = $m;
                include $routeFile;

                if ($this->configBase !== '') {
                    $localRouteFile = $this->configBase . '/' . $app . '/routes.local.php';
                    if (file_exists($localRouteFile)) {
                        include $localRouteFile;
                    }
                }

                $inAppLocal = $fileroot . '/config/routes.local.php';
                if (file_exists($inAppLocal)) {
                    include $inAppLocal;
                }
            });

            $afterCount = count($mapper->getMatchList());
            $added = $afterCount - $beforeCount;
            if ($added > 0) {
                $appCount++;
                $routeCount += $added;
            }
        }

        if ($this->configBase !== '') {
            $globalRoutes = $this->configBase . '/routes.php';
            if (file_exists($globalRoutes)) {
                $m = $mapper;
                include $globalRoutes;
                $routeCount = count($mapper->getMatchList());
            }
        }

        $compiled = $mapper->dump();

        if (!is_dir($this->cacheDir)) {
            if (!mkdir($this->cacheDir, 0755, true)) {
                throw new RuntimeException(
                    'Cannot create cache directory: ' . $this->cacheDir
                );
            }
        }

        $outputFile = $this->cacheDir . '/routes.compiled.php';
        $content = "<?php\n\n// Auto-generated by RoutesCompiler at " . date('Y-m-d H:i:s') . "\n"
            . "// Do not edit - regenerate with: php bin/horde-routes-compile\n\n"
            . "return " . var_export($compiled, true) . ";\n";

        if (file_put_contents($outputFile, $content) === false) {
            throw new RuntimeException(
                'Failed to write compiled routes to: ' . $outputFile
            );
        }

        return new RoutesCompilerResult(
            appCount: $appCount,
            routeCount: $routeCount,
            outputFile: $outputFile,
            compiled: $compiled,
        );
    }
}
