<?php

/**
 * Copyright 2015-2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category  Horde
 * @copyright 2015-2026 The Horde Project
 * @license   http://www.horde.org/licenses/lgpl21 LGPL
 * @package   Core
 */

use Horde\Core\Secret\HkdfInfo;
use Horde\Core\Secret\SessionSecret;
use Horde\Core\Session\HordeSession;
use Horde\Crypt\Blowfish\Blowfish;
use Horde\Exception\HordeRuntimeException;

/**
 * Horde_Secret, using a per-session derived key, with CBC Blowfish encryption.
 *
 * The class supports three formats for the per-session key, selected
 * by the `key_format` constructor parameter:
 *
 *   - `hkdf-only` — Reads and writes only the HKDF (shape-3) format.
 *     Sessions in the older PR-#174 shape (raw key at `_secret/key`)
 *     are treated as having no readable key; their encrypted slots
 *     degrade to "no credentials" and the user re-authenticates.
 *     Use after the user fleet has migrated.
 *
 *   - `hkdf-with-legacy-fallback` (default) — Writes HKDF shape, reads
 *     either HKDF or PR-#174 shape. Sessions arriving in the older
 *     shape stay readable and are migrated to HKDF shape on the next
 *     rotation event. The normal mode during a deployment's migration
 *     window.
 *
 *   - `legacy-only` — Reads and writes only the PR-#174 shape (raw
 *     key at `_secret/key`). Bypasses HKDF entirely. Provided as an
 *     operator-controlled rollback path: a severe HKDF-side bug can
 *     be neutralised by flipping this setting without redeploying
 *     code. The cost of the flip is that any HKDF-shape sessions
 *     written before the flip become unreadable; those users
 *     re-authenticate.
 *
 * **HKDF derivation (shapes hkdf-* only).** The per-session Blowfish
 * key is derived per request via HKDF-SHA256 over three inputs:
 *
 *   1. `$conf['secret_key']` — operator-set, lives in `conf.php`.
 *   2. The per-session salt — 32 random bytes, lives in the session
 *      payload at `_secret/salt`. Generated by
 *      {@see Horde\Core\Session\HordeSessionFactory::createNew()} for
 *      fresh sessions and on first {@see setKey()} call thereafter.
 *   3. `session.id` — the current PHP session id.
 *
 * An attacker who exfiltrates the session row alone gets the salt
 * but not the operator's `secret_key` (which is on the server's
 * filesystem, not in the session backend) and not the `session.id`
 * (which is in the user's cookie jar). All three are needed to
 * reproduce the key.
 *
 * **Lifetime.** Configuration arrives in the constructor and is
 * stable for the object's lifetime. The session reference arrives
 * via {@see setSession()} because the session does not exist yet at
 * construction (the factory builds the secret service first, then
 * the session, then wires them); it rotates within a request when
 * {@see SessionLifecycle::clean()} or {@see SessionLifecycle::regenerate()}
 * rebuilds the HordeSession instance.
 *
 * @todo  Merge this class with Horde_Core_Secret.
 *
 * @author    Michael Slusarz <slusarz@horde.org>
 * @author    Ralf Lang <ralf.lang@ralf-lang.de>
 * @category  Horde
 * @copyright 2015-2026 The Horde Project
 * @license   http://www.horde.org/licenses/lgpl21 LGPL
 * @package   Core
 * @since     2.20.0
 */
class Horde_Core_Secret_Cbc extends Horde_Core_Secret implements SessionSecret
{
    /** Slot scope where the per-session key material lives in HordeSession. */
    private const SCOPE = '_secret';

    /** Slot name for the HKDF-era salt (shape-3). */
    private const SALT_NAME = 'salt';

    /** Slot name for the legacy / PR-#174 raw key (shape-2). */
    private const LEGACY_KEY_NAME = 'key';

    /** Salt size in bytes. */
    private const SALT_BYTES = 32;

    /** Blowfish maximum key size. */
    private const KEY_BYTES = 56;

    /** key_format constructor-param value: HKDF only, refuse legacy. */
    public const KEY_FORMAT_HKDF_ONLY = 'hkdf-only';

    /** key_format default: write HKDF, read either. */
    public const KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK = 'hkdf-with-legacy-fallback';

    /** key_format constructor-param value: PR-#174 shape only. Rollback. */
    public const KEY_FORMAT_LEGACY_ONLY = 'legacy-only';

    /** Valid values for the key_format constructor param. */
    private const VALID_KEY_FORMATS = [
        self::KEY_FORMAT_HKDF_ONLY,
        self::KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK,
        self::KEY_FORMAT_LEGACY_ONLY,
    ];

    /**
     * Key used for current cached cipher object.
     *
     * @var string
     */
    protected $_cachedKey = '';

    /**
     * Modern session, wired by {@see setSession()}. Null before wiring
     * (e.g. during DI bootstrap, before HordeSessionFactory has built
     * the session). The reference rotates within a request when the
     * lifecycle calls rebuildHordeSession(); each rotation re-invokes
     * setSession() on this instance so the field tracks the live
     * session.
     *
     * @var ?HordeSession
     */
    protected ?HordeSession $_session = null;

    /**
     * Operator-set master secret from `$conf['secret_key']`. Read
     * from the constructor's `$params['secret_key']`. The first of
     * the three HKDF inputs. Required for hkdf-* formats; unused for
     * legacy-only.
     */
    protected string $_configuredSecretKey = '';

    /**
     * Selected key format. One of the KEY_FORMAT_* constants. Stable
     * for the object's lifetime — comes from `$conf['session']['key_format']`,
     * which doesn't change mid-request.
     */
    protected string $_keyFormat = self::KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK;

    /**
     * Cached derived key. Stable within a request as long as the
     * `(salt, session_id)` pair does not change. Invalidated by
     * {@see setKey()} (writes a new salt) and {@see setSession()}
     * (may change the session id).
     *
     * @var string Empty until first derivation.
     */
    private string $_derivedKey = '';

    /**
     * Cache key for {@see $_derivedKey}: salt . "\0" . session_id().
     */
    private string $_derivedKeyCacheKey = '';

    /**
     * Constructor. Accepts the parent `$params` array plus two HKDF-
     * specific keys:
     *
     *   - `secret_key` (string): operator's master secret from
     *     `$conf['secret_key']`. Required for hkdf-* formats; may be
     *     empty for legacy-only.
     *   - `key_format` (string): one of the KEY_FORMAT_* constants.
     *     Defaults to KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK.
     *
     * Validates both at construction so a misconfigured operator
     * gets a loud failure during bootstrap rather than a silent
     * encryption-side bug later.
     *
     * @param array<string, mixed> $params Parent params plus the
     *                                     two new keys above.
     *
     * @throws HordeRuntimeException When key_format is not a valid
     *                               enum value, or when an hkdf-*
     *                               format is selected with an
     *                               empty secret_key.
     */
    public function __construct($params = [])
    {
        parent::__construct($params);

        $keyFormat = (string) ($this->_params['key_format']
            ?? self::KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK);
        if (!in_array($keyFormat, self::VALID_KEY_FORMATS, true)) {
            throw new HordeRuntimeException(sprintf(
                "Horde_Core_Secret_Cbc: invalid key_format '%s'. "
                . "Valid values are: '%s', '%s', '%s'.",
                $keyFormat,
                self::KEY_FORMAT_HKDF_ONLY,
                self::KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK,
                self::KEY_FORMAT_LEGACY_ONLY,
            ));
        }
        $this->_keyFormat = $keyFormat;

        $this->_configuredSecretKey = (string) ($this->_params['secret_key'] ?? '');
        if ($keyFormat !== self::KEY_FORMAT_LEGACY_ONLY
            && $this->_configuredSecretKey === '') {
            throw new HordeRuntimeException(
                "Horde_Core_Secret_Cbc: key_format '" . $keyFormat
                . "' requires a non-empty 'secret_key' constructor "
                . 'parameter. HKDF derivation over empty master '
                . "secret would produce a predictable per-session "
                . "key. Set a strong \$conf['secret_key'] in "
                . 'horde/conf.php, or switch key_format to '
                . "'" . self::KEY_FORMAT_LEGACY_ONLY . "' "
                . '(rollback mode).'
            );
        }
    }

    /**
     * Wire the modern session in. Called from
     * {@see Horde\Core\Session\HordeSessionFactory::create()} right after
     * the session is built. Re-invoked when the lifecycle rebuilds the
     * session (clean(), regenerate()-via-some-paths) so the reference
     * tracks the live instance.
     */
    public function setSession(HordeSession $session): void
    {
        $this->_session = $session;
        // The cached derivation is bound to the previous session's id;
        // invalidate so the next getKey() rebuilds against the new one.
        $this->_derivedKey = '';
        $this->_derivedKeyCacheKey = '';
    }

    /**
     */
    protected function _getCipherOb($key)
    {
        $key = substr($key, 0, self::KEY_BYTES);

        if (!isset($this->_cipherCache[self::HORDE_KEYNAME])
            || $this->_cachedKey !== $key) {
            $this->_cipherCache[self::HORDE_KEYNAME] = Blowfish::cbc(
                $key,
                $this->_params['iv']
            );
            $this->_cachedKey = $key;
        }

        return $this->_cipherCache[self::HORDE_KEYNAME];
    }

    /**
     * Return the per-session encryption key.
     *
     * Branches on {@see $_keyFormat}:
     *
     *  - legacy-only: read the raw key from `_secret/key`. If absent,
     *    mint a new one via {@see setKey()}.
     *  - hkdf-only: read the salt from `_secret/salt` and derive. If
     *    absent, mint a new salt via {@see setKey()}. A `_secret/key`
     *    slot, if present, is ignored.
     *  - hkdf-with-legacy-fallback: try HKDF first (`_secret/salt`).
     *    If absent, fall back to reading `_secret/key` as a raw key
     *    (shape-2 read). If both are absent, mint via {@see setKey()}.
     *
     * When the secret service has not been wired to a session, falls
     * back to legacy {@see Horde_Core_Secret::getKey()} for CLI /
     * bootstrap contexts.
     */
    public function getKey($keyname = self::DEFAULT_KEY)
    {
        if ($this->_session === null) {
            return parent::getKey($keyname);
        }

        if ($this->_keyFormat === self::KEY_FORMAT_LEGACY_ONLY) {
            return $this->readLegacyShape($keyname);
        }

        // hkdf-only and hkdf-with-legacy-fallback both prefer HKDF.
        if ($this->_session->hasScoped(self::SCOPE, self::SALT_NAME)) {
            $salt = $this->_session->getScoped(self::SCOPE, self::SALT_NAME);
            if (is_string($salt) && $salt !== '') {
                return $this->deriveKey($salt);
            }
        }

        // No HKDF salt. Decide whether legacy shape-2 is allowed.
        if ($this->_keyFormat === self::KEY_FORMAT_HKDF_WITH_LEGACY_FALLBACK
            && $this->_session->hasScoped(self::SCOPE, self::LEGACY_KEY_NAME)) {
            $stored = $this->_session->getScoped(self::SCOPE, self::LEGACY_KEY_NAME);
            if (is_string($stored) && $stored !== '') {
                return $stored;
            }
        }

        // hkdf-only with no salt slot, or fallback mode with neither
        // slot present. Mint per the current format.
        return $this->setKey($keyname);
    }

    /**
     * Set or rotate the per-session encryption key material.
     *
     * Under hkdf-* formats: writes a fresh 32-byte salt to
     * `_secret/salt` and drops any legacy `_secret/key` slot. The
     * actual key is re-derived on demand.
     *
     * Under legacy-only: mints a new random raw key (via the parent
     * class) and stores it at `_secret/key`. Drops any HKDF salt
     * slot so a future format change doesn't get confused state.
     *
     * Callers responsible for draining encrypted slots before
     * calling setKey, then refilling after, when they want to
     * preserve existing ciphertext across the rotation. The
     * {@see Horde\Core\Session\SessionEncryptionCoordinator}
     * arranges this.
     *
     * Falls back to parent's {@see setKey()} when the session is
     * not wired.
     */
    public function setKey($keyname = self::DEFAULT_KEY)
    {
        if ($this->_session === null) {
            return parent::setKey($keyname);
        }

        if ($this->_keyFormat === self::KEY_FORMAT_LEGACY_ONLY) {
            return $this->writeLegacyShape($keyname);
        }

        return $this->writeHkdfShape();
    }

    /**
     * Clear all per-session key material from the session payload.
     *
     * Drops both the HKDF salt and any legacy raw-key slot regardless
     * of the active key_format. Also clears the cached derived key
     * and cipher cache, and calls the parent to clear the legacy
     * cookie for cookies-still-present cleanup scenarios.
     */
    public function clearKey($keyname = self::DEFAULT_KEY)
    {
        if ($this->_session !== null) {
            $this->_session->removeScoped(self::SCOPE, self::SALT_NAME);
            $this->_session->removeScoped(self::SCOPE, self::LEGACY_KEY_NAME);
        }
        $this->_cachedKey = '';
        $this->_derivedKey = '';
        $this->_derivedKeyCacheKey = '';

        return parent::clearKey($keyname);
    }

    /**
     * Mint a fresh HKDF salt, persist it, and return the derived key.
     * Drops any legacy shape-2 slot as a side-effect (shape-2 →
     * shape-3 migration).
     */
    private function writeHkdfShape(): string
    {
        $salt = random_bytes(self::SALT_BYTES);
        $this->_session->setScoped(self::SCOPE, self::SALT_NAME, $salt);

        if ($this->_session->hasScoped(self::SCOPE, self::LEGACY_KEY_NAME)) {
            $this->_session->removeScoped(self::SCOPE, self::LEGACY_KEY_NAME);
        }

        $this->_cachedKey = '';
        $this->_derivedKey = '';
        $this->_derivedKeyCacheKey = '';

        return $this->deriveKey($salt);
    }

    /**
     * Mint a fresh raw key, persist it at `_secret/key`, and drop
     * any HKDF salt slot (so reads do not see a stale shape-3 salt
     * after a flip back to legacy-only).
     *
     * Deliberately does NOT delegate to `parent::setKey()`. The
     * parent reads `$_COOKIE[$session_name . '_key']` and reuses
     * that value as the key when present. Adopting a cookie value
     * is wrong for `legacy-only`, which is a rollback mode: the
     * operator's intent is "start fresh under the legacy contract,"
     * not "resurrect cookie state from a previous deployment
     * epoch." Cookie adoption would also give an attacker who
     * plants a `horde_secret_key` cookie in a victim's browser
     * control of the encryption key. We mint our own random value
     * and ignore the cookie entirely.
     */
    private function writeLegacyShape($keyname): string
    {
        $rawKey = strval(new Horde_Support_Randomid());

        $this->_session->setScoped(self::SCOPE, self::LEGACY_KEY_NAME, $rawKey);

        if ($this->_session->hasScoped(self::SCOPE, self::SALT_NAME)) {
            $this->_session->removeScoped(self::SCOPE, self::SALT_NAME);
        }

        $this->_cachedKey = '';
        $this->_derivedKey = '';
        $this->_derivedKeyCacheKey = '';

        return $rawKey;
    }

    /**
     * Read the raw legacy-shape key, or mint one when absent.
     *
     * Used by getKey() when key_format is legacy-only, and by the
     * fallback branch of hkdf-with-legacy-fallback when no salt slot
     * is present.
     */
    private function readLegacyShape($keyname): string
    {
        if ($this->_session->hasScoped(self::SCOPE, self::LEGACY_KEY_NAME)) {
            $stored = $this->_session->getScoped(self::SCOPE, self::LEGACY_KEY_NAME);
            if (is_string($stored) && $stored !== '') {
                return $stored;
            }
        }

        return $this->writeLegacyShape($keyname);
    }

    /**
     * Derive the per-session Blowfish key via HKDF-SHA256.
     *
     * Inputs:
     *  - ikm  = configuredSecretKey . salt
     *  - salt parameter = session_id()
     *  - info = HkdfInfo::SESSION_BLOWFISH_CBC_V1
     *  - length = 56 bytes (Blowfish max)
     *
     * Cached within the request keyed by `(salt, session_id)`.
     */
    private function deriveKey(string $salt): string
    {
        $sessionId = session_id();
        if (!is_string($sessionId)) {
            $sessionId = '';
        }

        $cacheKey = $salt . "\0" . $sessionId;
        if ($this->_derivedKey !== '' && $this->_derivedKeyCacheKey === $cacheKey) {
            return $this->_derivedKey;
        }

        $derived = hash_hkdf(
            'sha256',
            $this->_configuredSecretKey . $salt,
            self::KEY_BYTES,
            HkdfInfo::SESSION_BLOWFISH_CBC_V1,
            $sessionId,
        );

        $this->_derivedKey = $derived;
        $this->_derivedKeyCacheKey = $cacheKey;
        return $derived;
    }
}
