<?php

declare(strict_types=1);

namespace Horde\Core\Test\Unit\PageOutput;

use Horde\Core\Assets\JsDiscoverer;
use Horde\Core\Assets\JsDiscoveryResult;
use Horde\Core\PageOutput\AssetCollector;
use Horde\Core\PageOutput\DesktopChromeRenderer;
use Horde\Core\PageOutput\PageComposer;
use Horde\Core\PageOutput\PageContent;
use Horde\Core\PageOutput\RenderingMode;
use Horde\Core\PageOutput\ViewMode;
use Horde\Core\PageOutput\ViewModeConfigurator;
use Horde\Core\Sidebar\SidebarData;
use Horde\Core\Sidebar\SidebarRenderer;
use Horde\Core\Topbar\TopbarBuilder;
use Horde\Core\Topbar\TopbarData;
use Horde\Core\Topbar\TopbarRenderer;
use Horde\Http\ServerRequest;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

#[CoversClass(DesktopChromeRenderer::class)]
class DesktopChromeRendererTest extends TestCase
{
    /**
     * Per-test renderer assembly. Each parameter is optional; when omitted
     * the test gets a mock with sensible expectations for the renderPage()
     * call shape. Tests that care about a specific collaborator pass an
     * already-configured mock and assert on it.
     */
    private function createRenderer(
        ?AssetCollector $collector = null,
        ?MockObject $pageComposer = null,
        ?MockObject $configurator = null,
        ?MockObject $topbarBuilder = null,
        ?MockObject $topbarRenderer = null,
        ?MockObject $sidebarRenderer = null,
        ?MockObject $jsDiscoverer = null,
    ): DesktopChromeRenderer {
        return new DesktopChromeRenderer(
            $collector ?? new AssetCollector(),
            $pageComposer ?? $this->defaultPageComposer(),
            $configurator ?? $this->defaultConfigurator(),
            $topbarBuilder ?? $this->defaultTopbarBuilder(),
            $topbarRenderer ?? $this->defaultTopbarRenderer(),
            $sidebarRenderer ?? $this->defaultSidebarRenderer(),
            $jsDiscoverer ?? $this->defaultJsDiscoverer(),
        );
    }

    /** PageComposer is called once for renderHead and once for renderFoot. */
    private function defaultPageComposer(): MockObject
    {
        $mock = $this->createMock(PageComposer::class);
        $mock->expects($this->once())->method('renderHead')->willReturn('<head-html>');
        $mock->expects($this->once())->method('renderFoot')->willReturn('<foot-html>');
        return $mock;
    }

    /** ViewModeConfigurator is called exactly once per renderPage. */
    private function defaultConfigurator(): MockObject
    {
        $mock = $this->createMock(ViewModeConfigurator::class);
        $mock->expects($this->once())->method('configure');
        return $mock;
    }

    private function defaultTopbarBuilder(): MockObject
    {
        $mock = $this->createMock(TopbarBuilder::class);
        $mock->expects($this->once())
            ->method('build')
            ->willReturn(new TopbarData(portalUrl: '/horde/', version: 'H6'));
        return $mock;
    }

    private function defaultTopbarRenderer(): MockObject
    {
        $mock = $this->createMock(TopbarRenderer::class);
        $mock->expects($this->once())->method('render')->willReturn('<topbar-html>');
        return $mock;
    }

    /** SidebarRenderer fires only when PageContent carries sidebar data. */
    private function defaultSidebarRenderer(): MockObject
    {
        $mock = $this->createMock(SidebarRenderer::class);
        $mock->expects($this->never())->method('render');
        return $mock;
    }

    /** JsDiscoverer fires once per extra js file; default content has none. */
    private function defaultJsDiscoverer(): MockObject
    {
        $mock = $this->createMock(JsDiscoverer::class);
        $mock->expects($this->never())->method('resolve');
        $this->stubDiscoverTheme($mock);
        return $mock;
    }

    /**
     * The renderer always asks for theme scripts; stub an empty result since
     * JsDiscoveryResult is final and cannot be auto-generated by the mock.
     */
    private function stubDiscoverTheme(MockObject $mock): void
    {
        $mock->method('discoverTheme')
            ->willReturn(new JsDiscoveryResult([], 'default', 'horde'));
    }

    private function createRequest(RenderingMode $mode = RenderingMode::DYNAMIC): ServerRequest
    {
        $request = new ServerRequest('GET', 'http://localhost/horde/', [], null, '1.1', []);
        return $request->withAttribute('renderingMode', $mode);
    }

    #[Test]
    public function renderPageProducesHeadTopbarBodyFoot(): void
    {
        $renderer = $this->createRenderer();
        $content = new PageContent(title: 'Test Page', bodyHtml: '<div>Body</div>');

        $html = $renderer->renderPage($content, $this->createRequest());

        self::assertStringContainsString('<head-html>', $html);
        self::assertStringContainsString('<topbar-html>', $html);
        self::assertStringContainsString('<div>Body</div>', $html);
        self::assertStringContainsString('<foot-html>', $html);
    }

    #[Test]
    public function renderPageOrderIsCorrect(): void
    {
        $renderer = $this->createRenderer();
        $content = new PageContent(title: 'Test', bodyHtml: '<body-content>');

        $html = $renderer->renderPage($content, $this->createRequest());

        $headPos = strpos($html, '<head-html>');
        $topbarPos = strpos($html, '<topbar-html>');
        $bodyPos = strpos($html, '<body-content>');
        $footPos = strpos($html, '<foot-html>');

        self::assertLessThan($topbarPos, $headPos);
        self::assertLessThan($bodyPos, $topbarPos);
        self::assertLessThan($footPos, $bodyPos);
    }

    #[Test]
    public function renderPageIncludesSidebarWhenProvided(): void
    {
        // SidebarData present => sidebarRenderer must fire exactly once.
        $sidebarRenderer = $this->createMock(SidebarRenderer::class);
        $sidebarRenderer->expects($this->once())
            ->method('render')
            ->willReturn('<sidebar-html>');

        $renderer = $this->createRenderer(sidebarRenderer: $sidebarRenderer);
        $content = new PageContent(
            title: 'Test',
            bodyHtml: '<div>Body</div>',
            sidebarData: new SidebarData(),
        );

        $html = $renderer->renderPage($content, $this->createRequest());

        self::assertStringContainsString('<sidebar-html>', $html);
    }

    #[Test]
    public function renderPageSkipsSidebarWhenNull(): void
    {
        // Default sidebar mock already pins expects(never)->method('render').
        $renderer = $this->createRenderer();
        $content = new PageContent(title: 'Test', bodyHtml: '<div>Body</div>');

        $renderer->renderPage($content, $this->createRequest());
    }

    #[Test]
    public function renderPageConfiguresViewModeFromRequest(): void
    {
        $configurator = $this->createMock(ViewModeConfigurator::class);
        $configurator->expects($this->once())
            ->method('configure')
            ->with(self::isInstanceOf(AssetCollector::class), ViewMode::BASIC);

        $renderer = $this->createRenderer(configurator: $configurator);
        $content = new PageContent(title: 'Test', bodyHtml: '');

        $renderer->renderPage($content, $this->createRequest(RenderingMode::BASIC));
    }

    #[Test]
    public function renderPageDynamicModeUsesViewModeDynamic(): void
    {
        $configurator = $this->createMock(ViewModeConfigurator::class);
        $configurator->expects($this->once())
            ->method('configure')
            ->with(self::isInstanceOf(AssetCollector::class), ViewMode::DYNAMIC);

        $renderer = $this->createRenderer(configurator: $configurator);
        $content = new PageContent(title: 'Test', bodyHtml: '');

        $renderer->renderPage($content, $this->createRequest(RenderingMode::DYNAMIC));
    }

    #[Test]
    public function renderPageResolvesExtraJsFiles(): void
    {
        $collector = new AssetCollector();

        $jsDiscoverer = $this->createMock(JsDiscoverer::class);
        $jsDiscoverer->expects($this->once())
            ->method('resolve')
            ->with('tasks.js', 'nag')
            ->willReturn('/js/nag/tasks.js');
        $this->stubDiscoverTheme($jsDiscoverer);

        $renderer = $this->createRenderer(
            collector: $collector,
            jsDiscoverer: $jsDiscoverer,
        );
        $content = new PageContent(
            title: 'Test',
            bodyHtml: '',
            app: 'nag',
            jsFiles: ['tasks.js'],
        );

        $renderer->renderPage($content, $this->createRequest());

        $urls = $collector->getScriptUrls();
        self::assertContains('/js/nag/tasks.js', $urls);
    }

    #[Test]
    public function renderPageAddsExtraCssFiles(): void
    {
        $collector = new AssetCollector();

        $renderer = $this->createRenderer(collector: $collector);
        $content = new PageContent(
            title: 'Test',
            bodyHtml: '',
            cssFiles: ['/themes/default/custom.css'],
        );

        $renderer->renderPage($content, $this->createRequest());

        $urls = $collector->getStylesheetUrls();
        self::assertContains('/themes/default/custom.css', $urls);
    }

    #[Test]
    public function renderPageBuildsTopbarWithCorrectApp(): void
    {
        $topbarBuilder = $this->createMock(TopbarBuilder::class);
        $topbarBuilder->expects($this->once())
            ->method('build')
            ->with('imp')
            ->willReturn(new TopbarData(portalUrl: '/horde/', version: 'H6'));

        $renderer = $this->createRenderer(topbarBuilder: $topbarBuilder);
        $content = new PageContent(title: 'Mail', bodyHtml: '', app: 'imp');

        $renderer->renderPage($content, $this->createRequest());
    }

    #[Test]
    public function renderPageDefaultsModeWhenAttributeMissing(): void
    {
        $configurator = $this->createMock(ViewModeConfigurator::class);
        $configurator->expects($this->once())
            ->method('configure')
            ->with(self::isInstanceOf(AssetCollector::class), ViewMode::DYNAMIC);

        $renderer = $this->createRenderer(configurator: $configurator);
        $content = new PageContent(title: 'Test', bodyHtml: '');

        $request = new ServerRequest('GET', 'http://localhost/', [], null, '1.1', []);
        $renderer->renderPage($content, $request);
    }
}
